<?php
include("c:/xampp/htdocs/penilaian/koneksi.php");
$sql = "ALTER TABLE penilaian 
ADD COLUMN nilai4_1 INT(2) NULL DEFAULT NULL AFTER grade_nilai3,
ADD COLUMN nilai4_2 INT(2) NULL DEFAULT NULL AFTER nilai4_1,
ADD COLUMN nilai4_3 INT(2) NULL DEFAULT NULL AFTER nilai4_2,
ADD COLUMN nilai4_4 INT(2) NULL DEFAULT NULL AFTER nilai4_3,
ADD COLUMN nilai4_5 INT(2) NULL DEFAULT NULL AFTER nilai4_4,
ADD COLUMN nilai4_6 INT(2) NULL DEFAULT NULL AFTER nilai4_5,
ADD COLUMN nilai4_7 INT(2) NULL DEFAULT NULL AFTER nilai4_6,
ADD COLUMN nilai4_8 INT(2) NULL DEFAULT NULL AFTER nilai4_7,
ADD COLUMN nilai4_9 INT(2) NULL DEFAULT NULL AFTER nilai4_8,
ADD COLUMN nilai4_10 INT(2) NULL DEFAULT NULL AFTER nilai4_9,
ADD COLUMN nilai4_11 INT(2) NULL DEFAULT NULL AFTER nilai4_10,
ADD COLUMN nilai4_12 INT(2) NULL DEFAULT NULL AFTER nilai4_11,
ADD COLUMN nilai4_13 INT(2) NULL DEFAULT NULL AFTER nilai4_12,
ADD COLUMN nilai4_14 INT(2) NULL DEFAULT NULL AFTER nilai4_13,
ADD COLUMN nilai4_15 INT(2) NULL DEFAULT NULL AFTER nilai4_14,
ADD COLUMN nilai4_16 INT(2) NULL DEFAULT NULL AFTER nilai4_15,
ADD COLUMN nilai4_17 INT(2) NULL DEFAULT NULL AFTER nilai4_16,
ADD COLUMN nilai4_18 INT(2) NULL DEFAULT NULL AFTER nilai4_17,
ADD COLUMN nilai4_19 INT(2) NULL DEFAULT NULL AFTER nilai4_18,
ADD COLUMN total_nilai4 INT(3) NULL DEFAULT NULL AFTER nilai4_19,
ADD COLUMN rata_nilai4 DECIMAL(5,1) NULL DEFAULT NULL AFTER total_nilai4,
ADD COLUMN grade_nilai4 VARCHAR(3) NULL DEFAULT NULL AFTER rata_nilai4";

if(mysqli_query($koneksi, $sql)){
    echo "Success adding columns";
} else {
    echo "Error: " . mysqli_error($koneksi);
}
?>
